initial build (#1)
* docs: Added docs for usage and installation

* feat: :art: Started parsing arguments

* feat: :art: Finished working, had to use JS in the middle

diff --git a/gh-list-commits b/gh-list-commits
--- a/gh-list-commits
+++ b/gh-list-commits
@@ -1,37 +1,57 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Hello gh-list-commits!"
+# We have to accept 3 params:- owner, repo and PR number. Only PR Number is required.
+# We have to fetch the data using github cli like so
+# gh api /repos/{owner}/{repo}/pulls/{pull_number}/commits
+# After doing that, we need to parse the data that's returned, which will be an array and then we can simply print all of the shas of the commit.
 
-# Snippets to help get started:
+owner="{owner}"
+repo="{repo}"
+pull="-1"
 
-# Determine if an executable is in the PATH
-if ! type -p node >/dev/null; then
-  echo "Node not found on the system" >&2
+# Parse Arguments
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --repo=*)
+      repo="${1#*=}"
+      ;;
+    -R=*)
+      repo="${1#*=}"
+      ;;
+    -P=*)
+      pull="${1#*=}"
+      ;;
+    --pull=*)
+      pull="${1#*=}"
+      ;;
+    -O=*)
+      owner="${1#*=}"
+      ;;
+    --owner=*)
+      owner="${1#*=}"
+      ;;
+    *)
+      printf "***************************\n"
+      printf "* Error: Invalid argument.*\n"
+      printf "***************************\n"
+      exit 1
+  esac
+  shift
+done
+if [ $pull == "-1" ]; then
+  echo "Please provide a pull request number"
   exit 1
 fi
 
-echo "$@"
+# Get all commits using the github cli
+response=`gh api /repos/$owner/$repo/pulls/$pull/commits`
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
+echo $response > './gh-list-commits-results.json'
 
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+node -e '
+const path = require("path")
+require(
+    path.join(process.cwd(), "gh-list-commits-results.json")
+).forEach(commit => console.log(commit.sha))
+'
